name = "Mistcraft"
author = "Expertest"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d857acc2ac71061cb6725a2ddf3352c196a06ad49ce22b32b53f382ebcdde90"

[versions]
forge = "43.4.2"
minecraft = "1.19.2"
